package com.mysocialapp.android.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import com.mysocialapp.android.data.remote.UserDto

val AppShapes = Shapes(extraSmall = RoundedCornerShape(10.dp), small = RoundedCornerShape(14.dp), medium = RoundedCornerShape(20.dp), large = RoundedCornerShape(28.dp))
private val Brand = androidx.compose.ui.graphics.Color(0xFF6750A4)

@Composable fun AppTheme(content: @Composable () -> Unit) { MaterialTheme(colorScheme = if (isSystemInDarkTheme()) darkColorScheme(primary = androidx.compose.ui.graphics.Color(0xFFD0BCFF)) else lightColorScheme(primary = Brand, secondary = androidx.compose.ui.graphics.Color(0xFF526600)), shapes = AppShapes, content = content) }
@Composable fun AppScaffold(content: @Composable ColumnScope.() -> Unit) = Surface(Modifier.fillMaxSize()) { Column(Modifier.fillMaxSize().padding(horizontal = 24.dp).verticalScroll(rememberScrollState()), content = content) }
@Composable fun BrandLockup(tagline: String) { Spacer(Modifier.height(52.dp)); Text("MySocialApp", style = MaterialTheme.typography.displaySmall, color = MaterialTheme.colorScheme.primary); Spacer(Modifier.height(8.dp)); Text(tagline, style = MaterialTheme.typography.bodyLarge, color = MaterialTheme.colorScheme.onSurfaceVariant); Spacer(Modifier.height(32.dp)) }
@Composable fun ErrorNotice(message: String?) { if (message != null) { AssistChip(onClick = {}, label = { Text(message) }, colors = AssistChipDefaults.assistChipColors(containerColor = MaterialTheme.colorScheme.errorContainer, labelColor = MaterialTheme.colorScheme.onErrorContainer)); Spacer(Modifier.height(16.dp)) } }
@Composable fun Field(label: String, value: String, onChange: (String) -> Unit, password: Boolean = false, singleLine: Boolean = true) { OutlinedTextField(value, onValueChange = onChange, label = { Text(label) }, modifier = Modifier.fillMaxWidth(), singleLine = singleLine, visualTransformation = if (password) PasswordVisualTransformation() else androidx.compose.ui.text.input.VisualTransformation.None, keyboardOptions = KeyboardOptions(keyboardType = if (password) KeyboardType.Password else KeyboardType.Text)); Spacer(Modifier.height(12.dp)) }
@Composable fun WelcomeScreen(onLogin: () -> Unit, onRegister: () -> Unit) = AppScaffold { BrandLockup("A calmer place to share what matters."); Text("Your people. Your pace.", style = MaterialTheme.typography.headlineMedium); Spacer(Modifier.height(12.dp)); Text("Join a thoughtful community built around real conversations and meaningful connections.", style = MaterialTheme.typography.bodyLarge); Spacer(Modifier.weight(1f)); Button(onClick = onRegister, modifier = Modifier.fillMaxWidth().height(52.dp)) { Text("Create an account") }; Spacer(Modifier.height(12.dp)); OutlinedButton(onClick = onLogin, modifier = Modifier.fillMaxWidth().height(52.dp)) { Text("I already have an account") }; Spacer(Modifier.height(28.dp)) }
@Composable fun LoginScreen(loading: Boolean, error: String?, onBack: () -> Unit, onSubmit: (String, String) -> Unit, onRegister: () -> Unit) { var email by remember { mutableStateOf("") }; var password by remember { mutableStateOf("") }; AppScaffold { TextButton(onClick = onBack, modifier = Modifier.padding(top = 16.dp)) { Text("← Back") }; BrandLockup("Welcome back"); ErrorNotice(error); Field("Email", email, { email = it }); Field("Password", password, { password = it }, true); Button(onClick = { onSubmit(email, password) }, enabled = !loading && email.isNotBlank() && password.isNotBlank(), modifier = Modifier.fillMaxWidth().height(52.dp)) { if (loading) CircularProgressIndicator(Modifier.size(22.dp), strokeWidth = 2.dp) else Text("Sign in") }; TextButton(onClick = onRegister, modifier = Modifier.align(Alignment.CenterHorizontally)) { Text("New here? Create an account") } } }
@Composable fun RegisterScreen(loading: Boolean, error: String?, onBack: () -> Unit, onSubmit: (String, String, String, String) -> Unit) { var name by remember { mutableStateOf("") }; var username by remember { mutableStateOf("") }; var email by remember { mutableStateOf("") }; var password by remember { mutableStateOf("") }; AppScaffold { TextButton(onClick = onBack, modifier = Modifier.padding(top = 16.dp)) { Text("← Back") }; BrandLockup("Create your space"); ErrorNotice(error); Field("Your name", name, { name = it }); Field("Username", username, { username = it }); Field("Email", email, { email = it }); Field("Password", password, { password = it }, true); Text("Use 8+ characters with upper/lowercase letters and a number.", style = MaterialTheme.typography.labelMedium, color = MaterialTheme.colorScheme.onSurfaceVariant); Spacer(Modifier.height(16.dp)); Button(onClick = { onSubmit(username, name, email, password) }, enabled = !loading && listOf(name, username, email, password).all { it.isNotBlank() }, modifier = Modifier.fillMaxWidth().height(52.dp)) { if (loading) CircularProgressIndicator(Modifier.size(22.dp), strokeWidth = 2.dp) else Text("Create account") }; Spacer(Modifier.height(24.dp)) } }
@Composable fun HomeScreen(user: UserDto, onProfile: () -> Unit, onLogout: () -> Unit) = AppScaffold { Spacer(Modifier.height(32.dp)); Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween, verticalAlignment = Alignment.CenterVertically) { Column { Text("Good to see you,", style = MaterialTheme.typography.titleMedium); Text(user.name, style = MaterialTheme.typography.headlineMedium) }; TextButton(onClick = onLogout) { Text("Log out") } }; Spacer(Modifier.height(48.dp)); Card(Modifier.fillMaxWidth(), colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.secondaryContainer)) { Column(Modifier.padding(24.dp)) { Text("Your home is ready", style = MaterialTheme.typography.titleLarge); Spacer(Modifier.height(8.dp)); Text("Profile tools are available now. More ways to connect will arrive in future updates.") } }; Spacer(Modifier.height(24.dp)); Button(onClick = onProfile, modifier = Modifier.fillMaxWidth().height(52.dp)) { Text("View profile") } }
@Composable fun ProfileScreen(user: UserDto, onEdit: () -> Unit, onBack: () -> Unit) = AppScaffold { TextButton(onClick = onBack, modifier = Modifier.padding(top = 16.dp)) { Text("← Home") }; Spacer(Modifier.height(28.dp)); Surface(Modifier.size(88.dp), shape = RoundedCornerShape(44.dp), color = MaterialTheme.colorScheme.primaryContainer) { Box(contentAlignment = Alignment.Center) { Text(user.name.take(1).uppercase(), style = MaterialTheme.typography.displaySmall) } }; Spacer(Modifier.height(18.dp)); Text(user.name, style = MaterialTheme.typography.headlineMedium); Text("@${user.username}", color = MaterialTheme.colorScheme.onSurfaceVariant); Spacer(Modifier.height(20.dp)); Text(user.bio?.ifBlank { "No bio yet." } ?: "No bio yet.", style = MaterialTheme.typography.bodyLarge); Spacer(Modifier.height(30.dp)); OutlinedButton(onClick = onEdit, modifier = Modifier.fillMaxWidth().height(52.dp)) { Text("Edit profile") } }
@Composable fun EditProfileScreen(user: UserDto, loading: Boolean, error: String?, onBack: () -> Unit, onSave: (UserDto) -> Unit) { var name by remember { mutableStateOf(user.name) }; var username by remember { mutableStateOf(user.username) }; var email by remember { mutableStateOf(user.email.orEmpty()) }; var bio by remember { mutableStateOf(user.bio.orEmpty()) }; AppScaffold { TextButton(onClick = onBack, modifier = Modifier.padding(top = 16.dp)) { Text("← Cancel") }; Text("Edit profile", style = MaterialTheme.typography.headlineMedium); Spacer(Modifier.height(20.dp)); ErrorNotice(error); Field("Name", name, { name = it }); Field("Username", username, { username = it }); Field("Email", email, { email = it }); Field("Bio", bio, { bio = it }, singleLine = false); Button(onClick = { onSave(user.copy(name = name, username = username, email = email, bio = bio)) }, enabled = !loading, modifier = Modifier.fillMaxWidth().height(52.dp)) { if (loading) CircularProgressIndicator(Modifier.size(22.dp), strokeWidth = 2.dp) else Text("Save changes") } } }
